export const ADD_MESSAGE = 'ADD_MESSAGE';
export const LOAD_MESSAGES_PENDING = 'LOAD_MESSAGE_PENDING';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_ERROR = 'LOAD_MESSAGES_ERROR';